# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bagua',
            fields=[
                ('gua', models.CharField(max_length=250, primary_key='true', serialize=False)),
                ('fangwei', models.CharField(max_length=250)),
                ('qinshu', models.CharField(max_length=250)),
                ('yuzhou', models.CharField(max_length=250)),
                ('yinyang', models.CharField(max_length=250)),
                ('wuxing', models.CharField(max_length=250)),
                ('guaxiang', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Dizhi',
            fields=[
                ('dizhi', models.CharField(max_length=250, primary_key='true', serialize=False)),
                ('yinyang', models.CharField(max_length=250)),
                ('wuxing', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Huntianjiazi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gua', models.CharField(max_length=250)),
                ('neiwai', models.CharField(max_length=250)),
                ('chu', models.CharField(max_length=250)),
                ('er', models.CharField(max_length=250)),
                ('san', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Liuqin',
            fields=[
                ('wuxing', models.CharField(max_length=250, primary_key='true', serialize=False)),
                ('sheng', models.CharField(max_length=250)),
                ('ke', models.CharField(max_length=250)),
                ('beisheng', models.CharField(max_length=250)),
                ('beike', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Liushisigua',
            fields=[
                ('xu', models.IntegerField(primary_key='true', serialize=False)),
                ('gua', models.CharField(max_length=250)),
                ('gong', models.CharField(max_length=250)),
                ('waigua', models.CharField(max_length=250)),
                ('neigua', models.CharField(max_length=250)),
                ('shi', models.IntegerField()),
                ('ying', models.IntegerField()),
                ('liuchong', models.BooleanField()),
                ('liuhe', models.BooleanField()),
                ('youhun', models.BooleanField()),
                ('guihun', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Wuxing',
            fields=[
                ('wuxing', models.CharField(max_length=250, primary_key='true', serialize=False)),
                ('sheng', models.CharField(max_length=250)),
                ('ke', models.CharField(max_length=250)),
                ('beisheng', models.CharField(max_length=250)),
                ('beike', models.CharField(max_length=250)),
            ],
        ),
    ]
