# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-19 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liuyao', '0002_auto_20170517_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liuqin',
            old_name='wuxing',
            new_name='liuqin',
        ),
    ]
