# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-19 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liuyao', '0003_auto_20170520_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yao',
            fields=[
                ('yao', models.CharField(max_length=250, primary_key='true', serialize=False)),
                ('coin', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=250)),
                ('dong', models.BooleanField()),
            ],
        ),
    ]
