# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-19 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liuyao', '0004_yao'),
    ]

    operations = [
        migrations.AddField(
            model_name='yao',
            name='reverse',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
