class LiuYaoData:
    yao = [{"yao": "000", "coin": "无背", "name": "老阴", "image": "0", "dong": 1, "reverse": "1"},
           {"yao": "001", "coin": "一背", "name": "少阳", "image": "1", "dong": 0, "reverse": "0"},
           {"yao": "110", "coin": "二背", "name": "少阴", "image": "0", "dong": 0, "reverse": "1"},
           {"yao": "111", "coin": "三背", "name": "老阳", "image": "1", "dong": 1, "reverse": "0"}]

    wuxing = [{"wuxing": "土", "sheng": "金", "ke": "水", "beisheng": "火", "beike": "木"},
              {"wuxing": "木", "sheng": "火", "ke": "土", "beisheng": "水", "beike": "金"},
              {"wuxing": "水", "sheng": "木", "ke": "火", "beisheng": "金", "beike": "土"},
              {"wuxing": "火", "sheng": "土", "ke": "金", "beisheng": "木", "beike": "水"},
              {"wuxing": "金", "sheng": "水", "ke": "木", "beisheng": "土", "beike": "火"}]

    liushen = [
        {"rigan": "丁", "liuyao": "青龙", "wuyao": "玄武", "siyao": "白虎", "sanyao": "螣蛇", "eryao": "勾陈", "chuyao": "朱雀"},
        {"rigan": "丙", "liuyao": "青龙", "wuyao": "玄武", "siyao": "白虎", "sanyao": "螣蛇", "eryao": "勾陈", "chuyao": "朱雀"},
        {"rigan": "乙", "liuyao": "玄武", "wuyao": "白虎", "siyao": "螣蛇", "sanyao": "勾陈", "eryao": "朱雀", "chuyao": "青龙"},
        {"rigan": "壬", "liuyao": "白虎", "wuyao": "螣蛇", "siyao": "勾陈", "sanyao": "朱雀", "eryao": "青龙", "chuyao": "玄武"},
        {"rigan": "己", "liuyao": "勾陈", "wuyao": "朱雀", "siyao": "青龙", "sanyao": "玄武", "eryao": "白虎", "chuyao": "螣蛇"},
        {"rigan": "庚", "liuyao": "螣蛇", "wuyao": "勾陈", "siyao": "朱雀", "sanyao": "青龙", "eryao": "玄武", "chuyao": "白虎"},
        {"rigan": "戊", "liuyao": "朱雀", "wuyao": "青龙", "siyao": "玄武", "sanyao": "白虎", "eryao": "螣蛇", "chuyao": "勾陈"},
        {"rigan": "癸", "liuyao": "白虎", "wuyao": "螣蛇", "siyao": "勾陈", "sanyao": "朱雀", "eryao": "青龙", "chuyao": "玄武"},
        {"rigan": "辛", "liuyao": "螣蛇", "wuyao": "勾陈", "siyao": "朱雀", "sanyao": "青龙", "eryao": "玄武", "chuyao": "白虎"},
        {"rigan": "甲", "liuyao": "玄武", "wuyao": "白虎", "siyao": "螣蛇", "sanyao": "勾陈", "eryao": "朱雀", "chuyao": "青龙"}]

    liuqin = [{"liuqin": "兄弟", "sheng": "子孙", "ke": "妻财", "beisheng": "父母", "beike": "官鬼"},
              {"liuqin": "妻财", "sheng": "官鬼", "ke": "父母", "beisheng": "子孙", "beike": "兄弟"},
              {"liuqin": "子孙", "sheng": "妻财", "ke": "官鬼", "beisheng": "兄弟", "beike": "父母"},
              {"liuqin": "官鬼", "sheng": "父母", "ke": "兄弟", "beisheng": "妻财", "beike": "子孙"},
              {"liuqin": "父母", "sheng": "兄弟", "ke": "子孙", "beisheng": "官鬼", "beike": "妻财"}]

    huntianjiazi = [{"id": 1, "gua": "乾", "neiwai": "内", "chu": "子", "er": "寅", "san": "辰"},
                    {"id": 2, "gua": "坤", "neiwai": "内", "chu": "未", "er": "巳", "san": "卯"},
                    {"id": 3, "gua": "震", "neiwai": "内", "chu": "子", "er": "寅", "san": "辰"},
                    {"id": 4, "gua": "艮", "neiwai": "内", "chu": "辰", "er": "午", "san": "申"},
                    {"id": 5, "gua": "离", "neiwai": "内", "chu": "卯", "er": "丑", "san": "亥"},
                    {"id": 6, "gua": "坎", "neiwai": "内", "chu": "寅", "er": "辰", "san": "午"},
                    {"id": 7, "gua": "兑", "neiwai": "内", "chu": "巳", "er": "卯", "san": "丑"},
                    {"id": 8, "gua": "巽", "neiwai": "内", "chu": "丑", "er": "亥", "san": "酉"},
                    {"id": 9, "gua": "乾", "neiwai": "外", "chu": "午", "er": "申", "san": "戌"},
                    {"id": 10, "gua": "坤", "neiwai": "外", "chu": "丑", "er": "亥", "san": "酉"},
                    {"id": 11, "gua": "震", "neiwai": "外", "chu": "午", "er": "申", "san": "戌"},
                    {"id": 12, "gua": "艮", "neiwai": "外", "chu": "戌", "er": "子", "san": "寅"},
                    {"id": 13, "gua": "离", "neiwai": "外", "chu": "酉", "er": "未", "san": "巳"},
                    {"id": 14, "gua": "坎", "neiwai": "外", "chu": "申", "er": "戌", "san": "子"},
                    {"id": 15, "gua": "兑", "neiwai": "外", "chu": "亥", "er": "酉", "san": "未"},
                    {"id": 16, "gua": "巽", "neiwai": "外", "chu": "未", "er": "巳", "san": "卯"}]

    tianganxu = {"丁": 4 , "丙": 3, "乙": 2, "壬": 9, "己": 6, "庚": 7, "戊": 5, "癸": 10, "辛": 8, "甲": 1}

    dizhixu = {"子": 1, "丑": 2, "寅": 3, "卯": 4, "辰": 5, "巳": 6, "午": 7, "未": 8, "申": 9, "酉": 10, "戌": 11, "亥": 12}

    xunkong = {0:"戌亥", 10:"申酉", 8:"午未", 6:"辰巳", 4:"寅卯", 2:"子丑",}

    dizhi = [{"dizhi": "丑", "yinyang": "阴", "wuxing": "土"}, {"dizhi": "亥", "yinyang": "阳", "wuxing": "水"},
             {"dizhi": "午", "yinyang": "阳", "wuxing": "火"}, {"dizhi": "卯", "yinyang": "阳", "wuxing": "木"},
             {"dizhi": "子", "yinyang": "阳", "wuxing": "水"}, {"dizhi": "寅", "yinyang": "阳", "wuxing": "木"},
             {"dizhi": "巳", "yinyang": "阳", "wuxing": "火"}, {"dizhi": "戌", "yinyang": "阳", "wuxing": "土"},
             {"dizhi": "未", "yinyang": "阳", "wuxing": "土"}, {"dizhi": "申", "yinyang": "阳", "wuxing": "金"},
             {"dizhi": "辰", "yinyang": "阳", "wuxing": "土"}, {"dizhi": "酉", "yinyang": "阳", "wuxing": "金"}]

    bagua = [
        {"gua": "乾", "fangwei": "西北", "qinshu": "父", "yuzhou": "天", "yinyang": "阳", "wuxing": "金", "guaxiang": "111"},
        {"gua": "兑", "fangwei": "西", "qinshu": "少女", "yuzhou": "泽", "yinyang": "阴", "wuxing": "金", "guaxiang": "011"},
        {"gua": "坎", "fangwei": "北", "qinshu": "中男", "yuzhou": "水", "yinyang": "阳", "wuxing": "水", "guaxiang": "010"},
        {"gua": "坤", "fangwei": "西南", "qinshu": "母", "yuzhou": "地", "yinyang": "阴", "wuxing": "土", "guaxiang": "000"},
        {"gua": "巽", "fangwei": "东南", "qinshu": "长女", "yuzhou": "风", "yinyang": "阴", "wuxing": "木", "guaxiang": "110"},
        {"gua": "离", "fangwei": "南", "qinshu": "中女", "yuzhou": "火", "yinyang": "阴", "wuxing": "火", "guaxiang": "101"},
        {"gua": "艮", "fangwei": "东北", "qinshu": "少男", "yuzhou": "山", "yinyang": "阳", "wuxing": "土", "guaxiang": "100"},
        {"gua": "震", "fangwei": "东", "qinshu": "长男", "yuzhou": "雷", "yinyang": "阳", "wuxing": "木", "guaxiang": "001"}]

    liushisigua = [
        {"xu": 1, "gua": "乾为天", "gong": "乾", "waigua": "乾", "neigua": "乾", "shi": 6, "ying": 3, "liuchong": 1,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 2, "gua": "坤为地", "gong": "坤", "waigua": "坤", "neigua": "坤", "shi": 6, "ying": 3, "liuchong": 1,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 3, "gua": "水雷屯", "gong": "坎", "waigua": "坎", "neigua": "震", "shi": 2, "ying": 5, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 4, "gua": "山水蒙", "gong": "离", "waigua": "艮", "neigua": "坎", "shi": 4, "ying": 1, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 5, "gua": "水天需", "gong": "坤", "waigua": "坎", "neigua": "乾", "shi": 4, "ying": 1, "liuchong": 0,
         "liuhe": 0, "youhun": 1, "guihun": 0},
        {"xu": 6, "gua": "天水讼", "gong": "离", "waigua": "乾", "neigua": "坎", "shi": 4, "ying": 1, "liuchong": 0,
         "liuhe": 0, "youhun": 1, "guihun": 0},
        {"xu": 7, "gua": "地水师", "gong": "坎", "waigua": "坤", "neigua": "坎", "shi": 3, "ying": 6, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 1},
        {"xu": 8, "gua": "水地比", "gong": "坤", "waigua": "坎", "neigua": "坤", "shi": 3, "ying": 6, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 1},
        {"xu": 9, "gua": "风天小畜", "gong": "巽", "waigua": "巽", "neigua": "乾", "shi": 1, "ying": 4, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 10, "gua": "天泽履", "gong": "艮", "waigua": "乾", "neigua": "兑", "shi": 5, "ying": 2, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 11, "gua": "地天泰", "gong": "坤", "waigua": "坤", "neigua": "乾", "shi": 3, "ying": 6, "liuchong": 0,
         "liuhe": 1, "youhun": 0, "guihun": 0},
        {"xu": 12, "gua": "天地否", "gong": "乾", "waigua": "乾", "neigua": "坤", "shi": 3, "ying": 6, "liuchong": 0,
         "liuhe": 1, "youhun": 0, "guihun": 0},
        {"xu": 13, "gua": "天火同人", "gong": "离", "waigua": "乾", "neigua": "离", "shi": 3, "ying": 6, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 1},
        {"xu": 14, "gua": "火天大有", "gong": "乾", "waigua": "离", "neigua": "乾", "shi": 3, "ying": 6, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 1},
        {"xu": 15, "gua": "地山谦", "gong": "兑", "waigua": "坤", "neigua": "艮", "shi": 5, "ying": 2, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 16, "gua": "雷地豫", "gong": "震", "waigua": "震", "neigua": "坤", "shi": 1, "ying": 4, "liuchong": 0,
         "liuhe": 1, "youhun": 0, "guihun": 0},
        {"xu": 17, "gua": "泽雷随", "gong": "震", "waigua": "兑", "neigua": "震", "shi": 3, "ying": 6, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 1},
        {"xu": 18, "gua": "山风蛊", "gong": "巽", "waigua": "艮", "neigua": "巽", "shi": 3, "ying": 6, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 1},
        {"xu": 19, "gua": "地泽临", "gong": "坤", "waigua": "坤", "neigua": "兑", "shi": 2, "ying": 5, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 20, "gua": "风地观", "gong": "乾", "waigua": "巽", "neigua": "坤", "shi": 4, "ying": 1, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 21, "gua": "火雷噬嗑", "gong": "巽", "waigua": "离", "neigua": "震", "shi": 5, "ying": 2, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 22, "gua": "山火贲", "gong": "艮", "waigua": "艮", "neigua": "离", "shi": 1, "ying": 4, "liuchong": 0,
         "liuhe": 1, "youhun": 0, "guihun": 0},
        {"xu": 23, "gua": "山地剥", "gong": "乾", "waigua": "艮", "neigua": "坤", "shi": 5, "ying": 2, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 24, "gua": "地雷复", "gong": "坤", "waigua": "坤", "neigua": "震", "shi": 1, "ying": 4, "liuchong": 0,
         "liuhe": 1, "youhun": 0, "guihun": 0},
        {"xu": 25, "gua": "天雷无妄", "gong": "巽", "waigua": "乾", "neigua": "震", "shi": 4, "ying": 1, "liuchong": 1,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 26, "gua": "山天大畜", "gong": "艮", "waigua": "艮", "neigua": "乾", "shi": 2, "ying": 5, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 27, "gua": "山雷颐", "gong": "巽", "waigua": "艮", "neigua": "震", "shi": 4, "ying": 1, "liuchong": 0,
         "liuhe": 0, "youhun": 1, "guihun": 0},
        {"xu": 28, "gua": "泽风大过", "gong": "震", "waigua": "兑", "neigua": "巽", "shi": 4, "ying": 1, "liuchong": 0,
         "liuhe": 0, "youhun": 1, "guihun": 0},
        {"xu": 29, "gua": "坎为水", "gong": "坎", "waigua": "坎", "neigua": "坎", "shi": 6, "ying": 3, "liuchong": 1,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 30, "gua": "离为火", "gong": "离", "waigua": "离", "neigua": "离", "shi": 6, "ying": 3, "liuchong": 1,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 31, "gua": "泽山咸", "gong": "兑", "waigua": "兑", "neigua": "艮", "shi": 3, "ying": 6, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 32, "gua": "雷风恒", "gong": "震", "waigua": "震", "neigua": "巽", "shi": 3, "ying": 6, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 33, "gua": "天山遯", "gong": "乾", "waigua": "乾", "neigua": "艮", "shi": 2, "ying": 5, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 34, "gua": "雷天大壮", "gong": "坤", "waigua": "震", "neigua": "乾", "shi": 4, "ying": 1, "liuchong": 1,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 35, "gua": "火地晋", "gong": "乾", "waigua": "离", "neigua": "坤", "shi": 4, "ying": 1, "liuchong": 0,
         "liuhe": 0, "youhun": 1, "guihun": 0},
        {"xu": 36, "gua": "地火明夷", "gong": "坎", "waigua": "坤", "neigua": "离", "shi": 4, "ying": 1, "liuchong": 0,
         "liuhe": 0, "youhun": 1, "guihun": 0},
        {"xu": 37, "gua": "风火家人", "gong": "巽", "waigua": "巽", "neigua": "离", "shi": 2, "ying": 5, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 38, "gua": "火泽睽", "gong": "艮", "waigua": "离", "neigua": "兑", "shi": 4, "ying": 1, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 39, "gua": "水山蹇", "gong": "兑", "waigua": "坎", "neigua": "艮", "shi": 4, "ying": 1, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 40, "gua": "雷水解", "gong": "震", "waigua": "震", "neigua": "坎", "shi": 2, "ying": 5, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 41, "gua": "山泽损", "gong": "艮", "waigua": "艮", "neigua": "兑", "shi": 3, "ying": 6, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 42, "gua": "风雷益", "gong": "巽", "waigua": "巽", "neigua": "震", "shi": 3, "ying": 6, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 43, "gua": "泽天夬", "gong": "坤", "waigua": "兑", "neigua": "乾", "shi": 5, "ying": 2, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 44, "gua": "天风姤", "gong": "乾", "waigua": "乾", "neigua": "巽", "shi": 1, "ying": 4, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 45, "gua": "泽地萃", "gong": "兑", "waigua": "兑", "neigua": "坤", "shi": 2, "ying": 5, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 46, "gua": "地风升", "gong": "震", "waigua": "坤", "neigua": "巽", "shi": 4, "ying": 1, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 47, "gua": "泽水困", "gong": "兑", "waigua": "兑", "neigua": "坎", "shi": 1, "ying": 4, "liuchong": 0,
         "liuhe": 1, "youhun": 0, "guihun": 0},
        {"xu": 48, "gua": "水风井", "gong": "震", "waigua": "坎", "neigua": "巽", "shi": 5, "ying": 2, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 49, "gua": "泽火革", "gong": "坎", "waigua": "兑", "neigua": "离", "shi": 4, "ying": 1, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 50, "gua": "火风鼎", "gong": "离", "waigua": "离", "neigua": "巽", "shi": 2, "ying": 5, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 51, "gua": "震为雷", "gong": "震", "waigua": "震", "neigua": "震", "shi": 6, "ying": 3, "liuchong": 1,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 52, "gua": "艮为山", "gong": "艮", "waigua": "艮", "neigua": "艮", "shi": 6, "ying": 3, "liuchong": 1,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 53, "gua": "风山渐", "gong": "艮", "waigua": "巽", "neigua": "艮", "shi": 3, "ying": 6, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 1},
        {"xu": 54, "gua": "雷泽归妹", "gong": "兑", "waigua": "震", "neigua": "兑", "shi": 3, "ying": 6, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 1},
        {"xu": 55, "gua": "雷火丰", "gong": "坎", "waigua": "震", "neigua": "离", "shi": 5, "ying": 2, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 56, "gua": "火山旅", "gong": "离", "waigua": "离", "neigua": "艮", "shi": 1, "ying": 4, "liuchong": 0,
         "liuhe": 1, "youhun": 0, "guihun": 0},
        {"xu": 57, "gua": "巽为风", "gong": "巽", "waigua": "巽", "neigua": "巽", "shi": 6, "ying": 3, "liuchong": 1,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 58, "gua": "兑为泽", "gong": "兑", "waigua": "兑", "neigua": "兑", "shi": 6, "ying": 3, "liuchong": 1,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 59, "gua": "风水涣", "gong": "离", "waigua": "巽", "neigua": "坎", "shi": 5, "ying": 2, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 60, "gua": "水泽节", "gong": "坎", "waigua": "坎", "neigua": "兑", "shi": 1, "ying": 4, "liuchong": 0,
         "liuhe": 1, "youhun": 0, "guihun": 0},
        {"xu": 61, "gua": "风泽中孚", "gong": "艮", "waigua": "巽", "neigua": "兑", "shi": 4, "ying": 1, "liuchong": 0,
         "liuhe": 0, "youhun": 1, "guihun": 0},
        {"xu": 62, "gua": "雷山小过", "gong": "兑", "waigua": "震", "neigua": "艮", "shi": 4, "ying": 1, "liuchong": 0,
         "liuhe": 0, "youhun": 1, "guihun": 0},
        {"xu": 63, "gua": "水火既济", "gong": "坎", "waigua": "坎", "neigua": "离", "shi": 3, "ying": 6, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 0},
        {"xu": 64, "gua": "火水未济", "gong": "离", "waigua": "离", "neigua": "坎", "shi": 3, "ying": 6, "liuchong": 0,
         "liuhe": 0, "youhun": 0, "guihun": 0}]


    dizhi_name_set = ['liuyao_dizhi', 'wuyao_dizhi', 'siyao_dizhi', 'sanyao_dizhi', 'eryao_dizhi',
                    'chuyao_dizhi']
    wuxing_name_set = ['liuyao_wuxing', 'wuyao_wuxing', 'siyao_wuxing', 'sanyao_wuxing', 'eryao_wuxing',
                    'chuyao_wuxing']
    liuqin_name_set = ['liuyao_liuqin', 'wuyao_liuqin', 'siyao_liuqin', 'sanyao_liuqin', 'eryao_liuqin',
                    'chuyao_liuqin']
    liushen_name_set = ['liuyao_liushen', 'wuyao_liushen', 'siyao_liushen', 'sanyao_liushen', 'eryao_liushen',
                        'chuyao_liushen']

    dizhi_fushen_name_set = ['liuyao_fushen_dizhi', 'wuyao_fushen_dizhi', 'siyao_fushen_dizhi', 'sanyao_fushen_dizhi',
                            'eryao_fushen_dizhi',
                            'chuyao_fushen_dizhi']
    wuxing_fushen_name_set = ['liuyao_fushen_wuxing', 'wuyao_fushen_wuxing', 'siyao_fushen_wuxing', 'sanyao_fushen_wuxing',
                            'eryao_fushen_wuxing',
                            'chuyao_fushen_wuxing']
    liuqin_fushen_name_set = ['liuyao_fushen_liuqin', 'wuyao_fushen_liuqin', 'siyao_fushen_liuqin', 'sanyao_fushen_liuqin',
                            'eryao_fushen_liuqin',
                            'chuyao_fushen_liuqin']

    dizhi_feishen_name_set = ['liuyao_feishen_dizhi', 'wuyao_feishen_dizhi', 'siyao_feishen_dizhi', 'sanyao_feishen_dizhi',
                            'eryao_feishen_dizhi',
                            'chuyao_feishen_dizhi']
    wuxing_feishen_name_set = ['liuyao_feishen_wuxing', 'wuyao_feishen_wuxing', 'siyao_feishen_wuxing',
                            'sanyao_feishen_wuxing', 'eryao_feishen_wuxing',
                            'chuyao_feishen_wuxing']
    liuqin_feishen_name_set = ['liuyao_feishen_liuqin', 'wuyao_feishen_liuqin', 'siyao_feishen_liuqin',
                            'sanyao_feishen_liuqin', 'eryao_feishen_liuqin',
                            'chuyao_feishen_liuqin']

    yao_name_set = [
        {'label': '六爻', 'name': 'liuyao', 'time': 6},
        {'label': '五爻', 'name': 'wuyao', 'time': 5},
        {'label': '四爻', 'name': 'siyao', 'time': 4},
        {'label': '三爻', 'name': 'sanyao', 'time': 3},
        {'label': '二爻', 'name': 'eryao', 'time': 2},
        {'label': '初爻', 'name': 'chuyao', 'time': 1}
    ]

    gender_mapper = {
        'male': '男',
        'female': '女'
    }

    matter_mapper = {
        'shiye': '事业',
        'hunyin': '婚姻',
        'caiwu': '财物',
        'kaoshi': '考试',
        'xunren': '寻人',
        'xunwu': '寻物',
        'jiankang': '健康'
    }

    # 解卦用
    wang_xiang_xiu_qiu = [
        {
            '月': '寅',
            '子': '休囚',
            '丑': '休囚',
            '寅': '旺',
            '卯': '次旺',
            '辰': '休囚',
            '巳': '相',
            '午': '相',
            '未': '休囚',
            '申': '休囚',
            '酉': '休囚',
            '戌': '休囚',
            '亥': '休囚'
        },
        {
            '月': ' 卯',
            '子': '休囚',
            '丑': '休囚',
            '寅': '次旺',
            '卯': '旺',
            '辰': '休囚',
            '巳': '相',
            '午': '相',
            '未': '休囚',
            '申': '休囚',
            '酉': '休囚',
            '戌': '休囚',
            '亥': '休囚'
        },
        {
            '月': '辰',
            '子': '休囚',
            '丑': '次旺',
            '寅': '衰',
            '卯': '衰',
            '辰': '旺',
            '巳': '休囚',
            '午': '休囚',
            '未': '次旺',
            '申': '相',
            '酉': '相',
            '戌': '次次旺',
            '亥': '休囚'
        },
        {
            '月': '巳',
            '子': '休囚',
            '丑': '相',
            '寅': '休囚',
            '卯': '休囚',
            '辰': '相',
            '巳': '旺',
            '午': '次旺',
            '未': '相',
            '申': '休囚',
            '酉': '休囚',
            '戌': '相',
            '亥': '休囚'
        },
        {
            '月': '午',
            '子': '休囚',
            '丑': '相',
            '寅': '休囚',
            '卯': '休囚',
            '辰': '相',
            '巳': '次旺',
            '午': '旺',
            '未': '相',
            '申': '休囚',
            '酉': '休囚',
            '戌': '相',
            '亥': '休囚'
        },
        {
            '月': '未',
            '子': '休囚',
            '丑': '次次旺',
            '寅': '休囚',
            '卯': '休囚',
            '辰': '次旺',
            '巳': '衰',
            '午': '衰',
            '未': '旺',
            '申': '相',
            '酉': '相',
            '戌': '次旺',
            '亥': '休囚'
        },
        {
            '月': '申',
            '子': '相',
            '丑': '休囚',
            '寅': '休囚',
            '卯': '休囚',
            '辰': '休囚',
            '巳': '休囚',
            '午': '休囚',
            '未': '休囚',
            '申': '旺',
            '酉': '次旺',
            '戌': '休囚',
            '亥': '相',
        },
        {
            '月': '酉',
            '子': '相',
            '丑': '休囚',
            '寅': '休囚',
            '卯': '休囚',
            '辰': '休囚',
            '巳': '休囚',
            '午': '休囚',
            '未': '休囚',
            '申': '次旺',
            '酉': '旺',
            '戌': '休囚',
            '亥': '相',
        },
        {
            '月': '戌',
            '子': '休囚',
            '丑': '旺',
            '寅': '休囚',
            '卯': '休囚',
            '辰': '次旺',
            '巳': '休囚',
            '午': '休囚',
            '未': '旺',
            '申': '相',
            '酉': '相',
            '戌': '旺',
            '亥': '休囚'
        },
        {
            '月': '亥',
            '子': '次旺',
            '丑': '休囚',
            '寅': '相',
            '卯': '相',
            '辰': '休囚',
            '巳': '休囚',
            '午': '休囚',
            '未': '休囚',
            '申': '休囚',
            '酉': '休囚',
            '戌': '休囚',
            '亥': '旺',
        },
        {
            '月': '子',
            '子': '旺',
            '丑': '休囚',
            '寅': '相',
            '卯': '相',
            '辰': '休囚',
            '巳': '休囚',
            '午': '休囚',
            '未': '休囚',
            '申': '休囚',
            '酉': '休囚',
            '戌': '休囚',
            '亥': '次旺',
        },
        {
            '月': '丑',
            '子': '衰',
            '丑': '旺',
            '寅': '休囚',
            '卯': '休囚',
            '辰': '次旺',
            '巳': '休囚',
            '午': '次次旺',
            '未': '休囚',
            '申': '相',
            '酉': '相',
            '戌': '次旺',
            '亥': '衰'
        }
    ]

    dizhi_guanxi = [
        {
            '地支': '子',
            '子': '无',
            '丑': '合',
            '寅': '无',
            '卯': '无',
            '辰': '三合',
            '巳': '无',
            '午': '冲',
            '未': '无',
            '申': '三合',
            '酉': '无',
            '戌': '无',
            '亥': '无',
            '合': '水'
        },
        {
            '地支': '丑',
            '子': '合',
            '丑': '无',
            '寅': '无',
            '卯': '无',
            '辰': '无',
            '巳': '三合',
            '午': '无',
            '未': '冲',
            '申': '无',
            '酉': '三合',
            '戌': '无',
            '亥': '无',
            '合': '金'
        },
        {
            '地支': '寅',
            '子': '无',
            '丑': '无',
            '寅': '无',
            '卯': '无',
            '辰': '无',
            '巳': '无',
            '午': '三合',
            '未': '无',
            '申': '冲',
            '酉': '无',
            '戌': '三合',
            '亥': '合',
            '合': '火'
        },
        {
            '地支': '卯',
            '子': '无',
            '丑': '无',
            '寅': '无',
            '卯': '无',
            '辰': '无',
            '巳': '无',
            '午': '无',
            '未': '三合',
            '申': '无',
            '酉': '冲',
            '戌': '合',
            '亥': '三合',
            '合': '木'
        },
        {
            '地支': '辰',
            '子': '三合',
            '丑': '无',
            '寅': '无',
            '卯': '无',
            '辰': '无',
            '巳': '无',
            '午': '无',
            '未': '无',
            '申': '三合',
            '酉': '合',
            '戌': '冲',
            '亥': '无',
            '合': '水'
        },
        {
            '地支': '巳',
            '子': '无',
            '丑': '三合',
            '寅': '无',
            '卯': '无',
            '辰': '无',
            '巳': '无',
            '午': '无',
            '未': '无',
            '申': '合',
            '酉': '三合',
            '戌': '无',
            '亥': '冲',
            '合': '金'
        },
        {
            '地支': '午',
            '子': '冲',
            '丑': '无',
            '寅': '三合',
            '卯': '无',
            '辰': '无',
            '巳': '无',
            '午': '无',
            '未': '合',
            '申': '无',
            '酉': '无',
            '戌': '三合',
            '亥': '无',
            '合': '火'
        },
        {
            '地支': '未',
            '子': '无',
            '丑': '冲',
            '寅': '无',
            '卯': '三合',
            '辰': '无',
            '巳': '无',
            '午': '合',
            '未': '无',
            '申': '无',
            '酉': '无',
            '戌': '无',
            '亥': '三合',
            '合': '木'
        },
        {
            '地支': '申',
            '子': '三合',
            '丑': '无',
            '寅': '冲',
            '卯': '无',
            '辰': '三合',
            '巳': '合',
            '午': '无',
            '未': '无',
            '申': '无',
            '酉': '无',
            '戌': '无',
            '亥': '无',
            '合': '水'
        },
        {
            '地支': '酉',
            '子': '无',
            '丑': '三合',
            '寅': '无',
            '卯': '冲',
            '辰': '合',
            '巳': '三合',
            '午': '无',
            '未': '无',
            '申': '无',
            '酉': '无',
            '戌': '无',
            '亥': '无',
            '合': '金'
        },
        {
            '地支': '戌',
            '子': '无',
            '丑': '无',
            '寅': '三合',
            '卯': '合',
            '辰': '冲',
            '巳': '无',
            '午': '三合',
            '未': '无',
            '申': '无',
            '酉': '无',
            '戌': '无',
            '亥': '无',
            '合': '火'
        },
        {
            '地支': '亥',
            '子': '无',
            '丑': '无',
            '寅': '合',
            '卯': '三合',
            '辰': '无',
            '巳': '冲',
            '午': '无',
            '未': '三合',
            '申': '无',
            '酉': '无',
            '戌': '无',
            '亥': '无',
            '合': '木'
        },
    ]

    wuxing_guanxi = [
        {
            '五行': '金',
            '金': '比',
            '木': '无',
            '水': '无',
            '火': '克',
            '土': '生'
        },
        {
            '五行': '木',
            '金': '克',
            '木': '比',
            '水': '生',
            '火': '无',
            '土': '无'
        },
        {
            '五行': '水',
            '金': '生',
            '木': '无',
            '水': '比',
            '火': '无',
            '土': '克'
        },
        {
            '五行': '火',
            '金': '无',
            '木': '生',
            '水': '克',
            '火': '比',
            '土': '无'
        },
        {
            '五行': '土',
            '金': '无',
            '木': '克',
            '水': '无',
            '火': '生',
            '土': '比'
        }
    ]




